### ISSUE TITLE
Should use npm ci; not npm install

### ISSUE THREAD

**Issue by rjgotten** [RimuTec/AspNetCore.SpaServices.Extensions#1]
The suggested MSBuild target currently uses

```xml
<Exec WorkingDirectory="$(SpaRoot)" Command="npm install --no-optionals" />
```

This should use `npm ci` instead.

The `ci` command uses the exact version information and module graph from the `package-lock.json` file, whereas the base `install` command may install higher patch versions - which is unexpected behavior in the context of an automated restore.

**Comment by ManfredLange** [comment]
Great suggestion! 

Perhaps the build target could check if file `package-lock.json` exists and if that is the case run ```npm ci```. If `package-lock.json` is absent it should run ```npm install```.

**Comment by ManfredLange** [comment]
I've updated the the MSBuild target as follows:
- if file 'package-lock.json' is present, the command 'npm ci --no-optionals' is used
- if file 'package-lock.json' is absent, the command 'npm install --no-optionals' is used
- Either command is exectued only, if folder 'node_modules' is absent from '$(SpaRoot)' as specified in the csproj file
- Optiion `--no-optionals` is used to avoid a problem with fsevent (see https://github.com/fsevents/fsevents/issues/301)

I believe this change resolves this issue. 

@rjgotten Please confirm that this issue can now be closed. Thank you!

**Comment by ManfredLange** [comment]
@rjgotten Thank you for taking the time to submit this issue and to review the resolution!
