### ISSUE TITLE
Question regarding access to api controller

### ISSUE THREAD

**Issue by mmoore99** [RimuTec/AspNetCore.SpaServices.Extensions#2]
I forked your repo. When i startup the app everything works fine.  The url that is accessed is `https://localhost:5001/index.html` and the Hello World page is displayed.

If I try to access the WeatherForecast api controller at `https://localhost:5001/api/weatherforecast/get` I receive `Cannot GET /api/weatherforecast/get`.

Should I not be able to access the api controller in this manner? What am I missing?

**Comment by ManfredLange** [comment]
@mmoore99 Yes, you are right, you should be able to access the WeatherForecast endpoint. I'm looking into this and hope to provide a solution as soon as possible.

**Comment by ManfredLange** [comment]
Update: I can reproduce the issue and think that I have a solution which I'm hoping to be able to provide within the next couple of days.

**Comment by ManfredLange** [comment]
I've published a new version of the nuget package that solves this issue. I haven't updated the sample app yet. Once I have I intend to close this issue.

**Comment by ManfredLange** [comment]
The sample application has been updated to latest version, now demonstrating that you can indeed also reach endpoint `api/weatherforecast` as expected.

The API endpoint should not work again.

Please note that version 2.0.0 is now deleting files in `spaStaticFileOptions.RootPath` is running in a development environmnet.

**Comment by ManfredLange** [comment]
@mmoore99 Thank you, Mike, for taking the time to report this issue. Your help to improve this nuget package and the accompanying sample code is very much appreciated. :-)
